### ISSUE TITLE
theme on TIR is always the opposite of the theme on the main page

### ISSUE THREAD

**Issue by TheOliveOli38** [Tofutush/tofutush.github.io#1]
I uhhhh randomly discovered this
turns out that the main site uses value 0 for the light-dark variable for dark mode while TIR uses 1

also idk if my message on Neospring was sent (idk how it works and it didnt show up anywhere so im assuming it wasn't) so ill just say it again here: I love your stuff! I esp love how the dark mode color scheme looks on your sites, your art is wayy too good and so is all of the TIR stuff! (I must've spent at least a few hrs looking through most of it lmao)

**Comment by Tofutush** [comment]
aaarrggghh i did see your question on neosprings! it just doesn't show up until ive made a response.

and for the theme thing, you just reminded me that i changed the code for the tir site and forgot to paste it here! and also the browser is gonna put the two theme vars under the same namespace! so i need to fix that. thanks for telling me!

hmmmm now i have a choice, either to still use the same var name on both sites so the themes are always the same, or to use different names so changing the theme on one doesn't change the other. hmmm, which one do you think i should do?

**Comment by TheOliveOli38** [comment]
> aaarrggghh i did see your question on neosprings! it just doesn't show up until ive made a response.
Ohhh I see!
 
> hmmmm now i have a choice, either to still use the same var name on both sites so the themes are always the same, or to use different names so changing the theme on one doesn't change the other. hmmm, which one do you think i should do?
I think keeping the same variable names for both and just changing the code (on the main site, since changing the code for TIR would affect Neocities users who don't have that issue) is better imo, so users don't have to change modes for the sites individually

**Comment by Tofutush** [comment]
it should be fixed now, i think!

**Comment by TheOliveOli38** [comment]
I.... don't understand why but it's still not fixed, at least on my end? Even though it's exactly the same code????

I guess changing the variable name was the better choice after all...

![Image](https://github.com/user-attachments/assets/3b6a1fe3-2c60-48df-8839-0ccad4c6ad27)

![Image](https://github.com/user-attachments/assets/558b87a3-fd10-4928-a1bb-b360b56ed5ca)

**Comment by Tofutush** [comment]
hang on, i think i know. this site is missing parseInt. i missed that while copying from tir and i didnt copy the first line, thinking theyre exactly the same.

**Comment by Tofutush** [comment]
wait no i have it??

**Comment by Tofutush** [comment]
AAAHHH i know why! the DEFAULT theme on this site is dark and light on tir, and the code INVERTS stuff instead of SETTING stuff. i should change that

**Comment by TheOliveOli38** [comment]
Ohhhhhh that explains it

**Comment by Tofutush** [comment]
damn i should stop writing shit code and thinking "well it *could* work no big deal..." :laughcry:

**Comment by Tofutush** [comment]
thanks for catching this!! i hope its fixed now 😭
